using NUnit.Framework;

using ExonymsAPI.Service.Processors;

namespace ExonymsAPI.UnitTests.Service.Constructors
{
    public class GermanMiddleHighConstructorTests
    {
        private INameConstructor constructor;

        [SetUp]
        public void SetUp()
        {
            this.constructor = new NameConstructor();
        }

        [Test]
        [TestCase("Aalburg", "Alburc")]
        [TestCase("Aarschot", "Arsot")]
        [TestCase("Ackerhaus", "Akerhous")]
        [TestCase("Agrigent", "Agricent")]
        [TestCase("Ahrensberg", "Ahrenesbërc")]
        [TestCase("Ahrensburg", "Ahrenesburc")]
        [TestCase("Alitten", "Aliten")]
        [TestCase("Alkmaar", "Alkmar")]
        [TestCase("Alnwick", "Alnweich")]
        [TestCase("Alsfeld", "Alsfelt")]
        [TestCase("Altenberg", "Alternbërc")]
        [TestCase("Aschaffenburg", "Asafernburc")]
        [TestCase("Augsburg", "Augsburc")]
        [TestCase("Baden-Württemberg", "Badun-Würtembërc")]
        [TestCase("Balingen", "Balincen")]
        [TestCase("Battenberg", "Baternbërc")]
        [TestCase("Bayern", "Beiren")]
        [TestCase("Bechingen", "Bechincen")]
        [TestCase("Beichlingen", "Beichelincen")]
        [TestCase("Bergschlägen", "Bërcsläcen")]
        [TestCase("Bitburg", "Bitburc")]
        [TestCase("Blankenberg", "Blankernbërc")]
        [TestCase("Böblingen", "Böblincen")]
        [TestCase("Bökelnburg", "Bökelnburc")]
        [TestCase("Bonnhard", "Bunnhard")]
        [TestCase("Bräunlingen", "Bräunlincen")]
        [TestCase("Braunschweig-Lüneburg", "Brauneswích-Lüneburc")]
        [TestCase("Braunschweig", "Brauneswích")]
        [TestCase("Brauweiler", "Brouwílære")]
        [TestCase("Breisgau", "Breisachgöu")]
        [TestCase("Brixen", "Briccen")]
        [TestCase("Brokburg", "Bruchburc")]
        [TestCase("Bromberg", "Brombërc")]
        [TestCase("Bronckhorst", "Brunkhorst")]
        [TestCase("Brunasberg", "Braunesbërc")]
        [TestCase("Brüssel", "Brüzel")]
        [TestCase("Buchenland", "Buchenlant")]
        [TestCase("Buckenham", "Bökenheim")]
        [TestCase("Buckingham", "Bökingheim")]
        [TestCase("Burghausen", "Burchousen")]
        [TestCase("Burgund", "Burcund")]
        [TestCase("Burscheid", "Burseid")]
        [TestCase("Busiasch", "Busias")]
        [TestCase("Christburg", "Christburc")]
        [TestCase("Cloppenburg", "Cloppernburc")]
        [TestCase("Coburg", "Coburc")]
        [TestCase("Comburg", "Comburc")]
        [TestCase("Dagsburg", "Dagsburc")]
        [TestCase("Dannenberg", "Dannernbërc")]
        [TestCase("Darmstadt", "Darmstat")]
        [TestCase("Deutschland", "Deutslant")]
        [TestCase("Dieburg", "Diburc")]
        [TestCase("Diepenau", "Diepenöu")]
        [TestCase("Donnermund", "Thunnermund")]
        [TestCase("Dordrecht", "Thurchtrad")]
        [TestCase("Dörnberg", "Dörnbërc")]
        [TestCase("Dünaburg", "Dünaburc")]
        [TestCase("Ebersberg", "Eberesbërc")]
        [TestCase("Egerberg", "Ecerbërc")]
        [TestCase("Eidsborg", "Eidesborg")]
        [TestCase("Eilenburg", "Eilernburc")]
        [TestCase("Elburg", "Elburc")]
        [TestCase("Ellenbogen", "Ellernbocen")]
        [TestCase("Enschede", "Aniseide")]
        [TestCase("Essen", "Esnede")]
        [TestCase("Esslingen", "Ezlincen")]
        [TestCase("Ettelbruck", "Etelbrök")]
        [TestCase("Falkenberg", "Falkernbërc")]
        [TestCase("Farnsburg", "Farnesburc")]
        [TestCase("Finstingen", "Finestincen")]
        [TestCase("Flandern", "Flantern")]
        [TestCase("Fredriksten", "Fridrichstein")]
        [TestCase("Friesland", "Frislant")]
        [TestCase("Gallenberg", "Challernbërc")]
        [TestCase("Gallien", "Challin")]
        [TestCase("Gardelegen", "Chardelecen")]
        [TestCase("Gauchesholm", "Chouchesholm")]
        [TestCase("Gegensberg", "Checenesbërc")]
        [TestCase("Geislingen", "Cheislincen")]
        [TestCase("Geißeshaupt", "Cheizeshoupt")]
        [TestCase("Genf", "Chenf")]
        [TestCase("Gengeß", "Chengez")]
        [TestCase("Georgenburg", "Cheorcernburc")]
        [TestCase("Georgenthal", "Cheorcental")]
        [TestCase("Geraardsbergen", "Chærerdesbërcen")]
        [TestCase("Gilgenburg", "Chilcernburc")]
        [TestCase("Gleiberg", "Chleibërc")]
        [TestCase("Glenhausen", "Chlenhousen")]
        [TestCase("Glogau", "Chlogöu")]
        [TestCase("Goldingen", "Choldincen")]
        [TestCase("Göteborg", "Chöteborg")]
        [TestCase("Götzenburg", "Chötzernburc")]
        [TestCase("Grantabrücke", "Chrantabruke")]
        [TestCase("Gudensberg", "Chudunesbërc")]
        [TestCase("Güldenfurt", "Chüldunfurt")]
        [TestCase("Hachberg", "Hachbërc")]
        [TestCase("Hagenau", "Hacenöu")]
        [TestCase("Halland", "Hallant")]
        [TestCase("Hallsberg", "Hallebërc")]
        [TestCase("Halsingor", "Halsingar")]
        [TestCase("Hamburg", "Hamburc")]
        [TestCase("Hanau", "Hanöu")]
        [TestCase("Hannover", "Hanovere")]
        [TestCase("Hardenburg", "Hardunburc")]
        [TestCase("Hausweich", "Houswích")]
        [TestCase("Hedal", "Heital")]
        [TestCase("Hedmark", "Heidemark")]
        [TestCase("Heideck", "Heidek")]
        [TestCase("Heidelberg", "Heidelbërc")]
        [TestCase("Hengistburg", "Hengistburc")]
        [TestCase("Hennegau", "Hennegöu")]
        [TestCase("Hereford", "Heerfurt")]
        [TestCase("Hermannsburg", "Hermannesburc")]
        [TestCase("Herrevad", "Hehrewat")]
        [TestCase("Hersfeld", "Heresfelt")]
        [TestCase("Hertford", "Hirsfurt")]
        [TestCase("Hohenburg", "Hohernburc")]
        [TestCase("Hückeswagen", "Hükeswacen")]
        [TestCase("Hussburg", "Huzburc")]
        [TestCase("Innsbruck", "Innesbrök")]
        [TestCase("Jakobstadt", "Jakobstat")]
        [TestCase("Kanterberg", "Kanterbërc")]
        [TestCase("Kesselberg", "Kezelbërc")]
        [TestCase("Klausenburg", "Klousernburc")]
        [TestCase("Klingenberg", "Klincernbërc")]
        [TestCase("Kokelburg", "Kokelburc")]
        [TestCase("Königsberg", "Königsbërc")]
        [TestCase("Kreutzburg", "Kriutzburc")]
        [TestCase("Kreuzburg", "Kriuzburc")]
        [TestCase("Kreuznach", "Kriuzenach")]
        [TestCase("Kronstadt", "Krunestat")]
        [TestCase("Kuttenberg", "Kuternbërc")]
        [TestCase("Ladenburg", "Ladunburc")]
        [TestCase("Langenau", "Lancenöu")]
        [TestCase("Lauenburg", "Louernburc")]
        [TestCase("Lauenstein", "Louwenestein")]
        [TestCase("Lundenburg", "Lundunburc")]
        [TestCase("Lüneburg", "Lüneburc")]
        [TestCase("Mecklenburg", "Meklernburc")]
        [TestCase("Mühlhausen", "Mühelhousen")]
        [TestCase("Nordsiebenbürgen", "Nortsibernburcen")]
        [TestCase("Offenburg-Regen", "Ofernburc-Recen")]
        [TestCase("Rastenburg", "Rasternburc")]
        [TestCase("Rügenwalde", "Rücenwalde")]
        [TestCase("Salzberg", "Salzbërc")]
        [TestCase("Scharnikau", "Sarniköu")]
        [TestCase("Siebenbürgen", "Sibernburcen")]
        [TestCase("Taubenberg", "Toubernbërc")]
        [TestCase("Teuerstadt", "Teuerestat")]
        [TestCase("Törzburg", "Törzburc")]
        [TestCase("Tschenstochau", "Czenestochöu")]
        [TestCase("Tschernowitz", "Czernowitz")]
        [TestCase("Weißenburg", "Wízernburc")]
        [TestCase("Westfriesland", "Westfrislant")]
        [TestCase("Wiflisburg", "Wiflisburc")]
        [TestCase("Woldenberg", "Woldunbërc")]
        //[TestCase("Breitenau", "Breitenouwe")]
        //[TestCase("Habsburg", "Habichtsbërc")]
        public void GivenAGermanName_WhenConstructingTheMiddleHighGermanName_ThenTheCorrectNameIsReturned(
            string germanName,
            string middleHighGermanName)
            => Assert.That(constructor.Construct(germanName, "gmh"), Is.EqualTo(middleHighGermanName));
    }
}
